name: PlayStation Vita

on:
  pull_request:
    branches: [ master ]

jobs:
  psv:
    runs-on: ubuntu-18.04
    steps:
    - name: checkout fheroes2
      uses: actions/checkout@v2
      with:
        fetch-depth: 50
    - name: checkout pvs SDK
      uses: actions/checkout@v2
      with:
        repository: vitasdk/vdpm
        path: vdpm
        fetch-depth: 1
    - name: install packages
      run: sudo apt-get install uname
    - name: compile psv SDK
      run: cd vdpm && ./bootstrap-vitasdk.sh && ./install-all.sh
      env:
        VITASDK: /usr/local/vitasdk
        PATH: $VITASDK/bin:$PATH
    - name: compile
      run: make -f Makefile.vita
      env:
        VITASDK: /usr/local/vitasdk
        PATH: $VITASDK/bin:$PATH
        FHEROES2_STRICT_COMPILATION: "ON"
